import { motion } from 'framer-motion';
import { FileText, Brain, Target, BookOpen } from 'lucide-react';

const features = [
    {
        icon: FileText,
        title: 'Smart Resume Analysis',
        description: 'Upload your resume and our AI instantly extracts your skills, experience, and strengths to tailor your interview prep.',
    },
    {
        icon: Brain,
        title: 'AI Interview Questions',
        description: 'Get role-specific questions generated by AI based on your resume and the job profile you\'re targeting.',
    },
    {
        icon: Target,
        title: 'Role Matching',
        description: 'Discover which roles best match your skills and experience. Get honest, data-driven career guidance.',
    },
    {
        icon: BookOpen,
        title: 'Course Recommendations',
        description: 'Bridge your skill gaps with curated course suggestions tailored to your career goals and target role.',
    },
];

const containerVariants = {
    hidden: {},
    visible: {
        transition: {
            staggerChildren: 0.15,
        },
    },
};

const cardVariants = {
    hidden: { opacity: 0, y: 40 },
    visible: {
        opacity: 1,
        y: 0,
        transition: { duration: 0.6, ease: 'easeOut' },
    },
};

export default function Features() {
    return (
        <section id="features" className="relative py-24 sm:py-32">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Section Header */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: '-100px' }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-16"
                >
                    <span className="text-emerald-400 text-sm font-semibold tracking-widest uppercase">Features</span>
                    <h2 className="mt-3 text-3xl sm:text-4xl md:text-5xl font-bold">
                        Everything You Need to{' '}
                        <span className="gradient-text">Succeed</span>
                    </h2>
                    <p className="mt-4 text-gray-400 max-w-2xl mx-auto text-lg">
                        Our AI-powered platform gives you all the tools to prepare, practice, and excel in your interviews.
                    </p>
                </motion.div>

                
                <motion.div
                    variants={containerVariants}
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, margin: '-100px' }}
                    className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
                >
                    {features.map((feature) => {
                        const Icon = feature.icon;
                        return (
                            <motion.div
                                key={feature.title}
                                variants={cardVariants}
                                className="group glass glass-hover rounded-2xl p-6 transition-all duration-300 cursor-default"
                            >
                                <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center mb-5 group-hover:bg-emerald-500/20 group-hover:scale-110 transition-all duration-300">
                                    <Icon className="w-6 h-6 text-emerald-400" />
                                </div>
                                <h3 className="text-lg font-semibold text-white mb-2">{feature.title}</h3>
                                <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
                            </motion.div>
                        );
                    })}
                </motion.div>
            </div>
        </section>
    );
}
